### ISSUE TITLE
Enhancement request: enable use with VCFv4.2

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/sequence_utils#31]
https://github.com/galaxyproject/sequence_utils/blob/3112094fbc0c9b7fc13bb318a47216d11c65ca95/galaxy_utils/sequence/vcf.py#L63-L64

VCFv4.1 == ok
VCFv4.2 == tool fails with

```
            Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/maf/vcf_to_maf_customtrack.py", line 192, in <module>
    main()
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/maf/vcf_to_maf_customtrack.py", line 108, in main
    vcf_files.append(PopulationVCFParser(galaxy_utils.sequence.vcf.Reader(open(filename)), pop_name))
  File "/usr/local/lib/python3.7/site-packages/galaxy_utils/sequence/vcf.py", line 111, in __init__
    self.vcf_class = VariantCall.get_class_by_format(metadata_value)
  File "/usr/local/lib/python3.7/site-packages/galaxy_utils/sequence/vcf.py", line 15, in get_class_by_format
    assert format in VCF_FORMATS, 'Unknown format type specified: %s' % format
AssertionError: Unknown format type specified: VCFv4.2
```

**Comment by nsoranzo** [comment]
The latest version of the VCF format is 4.5, if anyone is interested in fixing this the differences among the various VCF version are listed at the end of https://samtools.github.io/hts-specs/VCFv4.5.pdf
